CREATE TABLE IF NOT EXISTS HERO_MISSION (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HEROID INT NOT NULL,
    MISSIONID INT NOT NULL,
    CONSTRAINT FK_Hero FOREIGN KEY (HEROID) REFERENCES HERO(id),
    CONSTRAINT FK_Mission FOREIGN KEY (MISSIONID) REFERENCES MISSION(ID)
);
