CREATE TABLE IF NOT EXISTS HEROE_MISSION (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HEROEID INT NOT NULL,
    MISSIONID INT NOT NULL,
    CONSTRAINT FK_HERO FOREIGN KEY (HEROEID) REFERENCES HEROE(ID),
    CONSTRAINT FK_MISSION FOREIGN KEY (MISSIONID) REFERENCES MISSION(ID)
);


