CREATE TABLE IF NOT EXISTS HERO_MISSION (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HEROID INT NOT NULL,
    MISSIONID INT NOT NULL,
    CONSTRAINT FK_HERO FOREIGN KEY (HEROID) REFERENCES HERO(ID),
    CONSTRAINT FK_MISSION FOREIGN KEY (MISSIONID) REFERENCES MISSION(ID)
);


