CREATE TABLE IF NOT EXISTS weapon (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name varchar(50) NOT NULL,
    HEROID int NOT NULL,
    CONSTRAINT FK_WEAPON FOREIGN KEY (HEROID) REFERENCES HERO(ID)
);
